### ISSUE TITLE
ParallelRunner doesn't recognize assumptions

### ISSUE THREAD

**Issue by christian-draeger** [MichaelTamm/junit-toolbox#12] opened 2017-01-16 17:26 UTC
hey, it seems to me that the ParallelRunner is having some issue with assumeTrue / assumeThat

i tryed something like

```@RunWith(ParallelRunner.class)
public class MyTest {
    @Test
    public void checkSomeThing() {
        assumeTrue(false);
        System.out.println("hello");
    }
}

if i run this test with ParallelRunner test is green and "hello" is printet to console. Without ParallelRunner test will be skipped as expected.

greetings
Chris

**Comment by efzwo** [comment] 2017-02-03 10:18
I had the exact same problem of unit tests not being skipped with AssumptionViolatedException.
It turned out to be an issue of ParallelRunner as it works correctly with the default JUnit runner.

**Comment by MichaelTamm** [comment] 2017-02-04 22:02
Hmm, I can not reproduce the bug.

I can confirm, that the test is marked as green and not as skipped -- which is hard too fix, because that's how JUnit 4 behaves by default, see: https://github.com/junit-team/junit4/blob/master/src/main/java/org/junit/runner/Result.java#L140

Nonetheless, `assumeTrue(false)` will still throw an `AssumptionViolatedException `and therefore `System.out.println("hello")` is not executed.

**Comment by efzwo** [comment] 2017-02-09 08:14
Ok, that's exactly what I ment. I did not try out if "hello" is printed out in this example.

But I have to disagree with you about the default behaviour of JUnit 4. Tests throwing an AssumptionViolationException are marked as skipped like those marked with the `@Ignore` annotation. I have JUnit 4.12 and tried this with Eclipse and IntelliJ IDEA.

**Comment by MichaelTamm** [comment] 2017-02-09 18:17
Eclipse / IntelliJ IDEA improve the default behaviour of JUnit. Nonetheless, that is a feature of Eclipse / IntelliJ IDEA and the default behaviour of JUnit is to ignored any `AssumptionViolatedException`.

I agree, that it would be nice, if skipped tests executed using the `ParallelRunner` would be marked as skipped when executed in a IDE, but unfortunately I don't know how to fix that.

**Comment by efzwo** [comment] 2017-02-10 08:03
Sorry, but I cannot agree with that. In a JUnit Test the AssumptionViolatedException is handled specially, see: https://github.com/junit-team/junit4/blob/master/src/main/java/org/junit/runners/ParentRunner.java#L328

But this code does obviously not run using the `ParallelRunner`.

**Comment by MichaelTamm** [comment] 2017-02-10 19:50
"... does obviously not run ..." -- Really? Did you set a breakpoint in the `runLeaf` method and executed a test annotated with `@RunWith(ParallelRunner.class)` to make sure you are right?

I guess not, because the `runLeaf` method **is** executed!

Please do a debug session and step into the methods starting from the breakpoint in the `runLeaf` method to see what is really happening ...

**Comment by efzwo** [comment] 2017-02-10 22:29
Well, I don't know what you are debugging, but the `AssumptionViolatedException` is catched and not rethrown here: https://github.com/junit-team/junit4/blob/master/src/main/java/org/junit/experimental/theories/Theories.java#L235

Thereby line 328 of ParentRunner will never execute in a `Theory`. The behavior is different in a standard Test, as the `AssumptionViolatedException` is handled in `ParentRunner` only.

**Comment by MichaelTamm** [comment] 2017-02-13 21:08
Sorry, my fault -- I can now reproduce, that line 327 in _ParentRunner.java_ (` eachNotifier.addFailedAssumption(e);`) is not executed when a `@Test` method throws an `AssumptionViolatedException`.

Nonetheless: This is the current behavior of the `Theories` runner, from which `ParallelRunner` is derived.

Therefore I think, this issue should be reported (and fixed) in the https://github.com/junit-team/junit4 project.

I don't think it is a good idea to change the handling of `AssumptionViolatedException`s in `ParallelRunner`, because it should be interchangeable with the `Theories` runner.

**Comment by efzwo** [comment] 2017-02-14 11:09
As already said, this is not a bug of the `Theories` runner but a feature which is described here: https://github.com/junit-team/junit4/wiki/Theories
> UserTest will attempt to run filenameIncludesUsername on every compatible DataPoint defined in the class. **If any of the assumptions fail, the data point is silently ignored.** If all of the assumptions pass, but an assertion fails, the test fails.

I apprechiate that you want to keep your runner interchangeable with the `Theories` runner. But your runner needs to handle more cases as it also runs for non-theory tests with the `@Test` annotation (which the `ParallelRunner` doesn't need to handle). If you want that runner to be compatible with `@Test` and `@Theory`, a solution could be to `handleAssumptionViolatedException` differently depending on the current annotation of the test.

**Comment by MichaelTamm** [comment] 2017-02-15 14:57
That sounds like a sensible idea to me (although I still think that behavior belongs into the `Theories` runner, because the `Theories` runner **can** handle `@Test` methods).

Would you like to update your pull request accordingly? And if so, please update `ParallelRunnerTest` too.

**Comment by christian-draeger** [comment] 2017-02-26 16:15
hey, 
i think @efzwo's idea to separate the behaviour of @Test and @Theory is good. since i'm not sure how to implement it easily (otherwise i would send a pull request) it would be awesome if one of you  could do that. thanks in advance and thanks for the nice project

**Comment by efzwo** [comment] 2017-02-28 12:00
I've updated my pull request accordingly.

**Closed** 2017-03-01 18:02 UTC

**Comment by efzwo** [comment] 2017-03-20 09:33
@MichaelTamm Could you please create a Maven package for v2.3?

**Comment by MichaelTamm** [comment] 2017-04-09 20:22
JUnit Toolbox 2.3 is in the central Maven repo now.
